/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as AboutRouteImport } from './routes/about'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemosIndexRouteImport } from './routes/demos/index'
import { Route as Demos_layoutRouteImport } from './routes/demos/__layout'
import { Route as DemosDemoIdRouteImport } from './routes/demos/$demoId'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appDashboardRouteRouteImport } from './routes/(app)/dashboard/route'
import { Route as appDashboardIndexRouteImport } from './routes/(app)/dashboard/index'
import { Route as appDashboardSettingsRouteImport } from './routes/(app)/dashboard/settings'
import { Route as appDashboardUsersIndexRouteImport } from './routes/(app)/dashboard/users/index'
import { Route as appDashboardEmployeesIndexRouteImport } from './routes/(app)/dashboard/employees/index'

const DemosRouteImport = createFileRoute('/demos')()

const DemosRoute = DemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosIndexRoute = DemosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemosRoute,
} as any)
const Demos_layoutRoute = Demos_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => DemosRoute,
} as any)
const DemosDemoIdRoute = DemosDemoIdRouteImport.update({
  id: '/demos/$demoId',
  path: '/demos/$demoId',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const appDashboardRouteRoute = appDashboardRouteRouteImport.update({
  id: '/(app)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const appDashboardIndexRoute = appDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardSettingsRoute = appDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardUsersIndexRoute = appDashboardUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => appDashboardRouteRoute,
} as any)
const appDashboardEmployeesIndexRoute =
  appDashboardEmployeesIndexRouteImport.update({
    id: '/employees/',
    path: '/employees/',
    getParentRoute: () => appDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof appDashboardRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/demos/$demoId': typeof DemosDemoIdRoute
  '/demos': typeof Demos_layoutRoute
  '/demos/': typeof DemosIndexRoute
  '/dashboard/settings': typeof appDashboardSettingsRoute
  '/dashboard/': typeof appDashboardIndexRoute
  '/dashboard/employees': typeof appDashboardEmployeesIndexRoute
  '/dashboard/users': typeof appDashboardUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/demos/$demoId': typeof DemosDemoIdRoute
  '/demos': typeof DemosIndexRoute
  '/dashboard/settings': typeof appDashboardSettingsRoute
  '/dashboard': typeof appDashboardIndexRoute
  '/dashboard/employees': typeof appDashboardEmployeesIndexRoute
  '/dashboard/users': typeof appDashboardUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/(app)/dashboard': typeof appDashboardRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/demos/$demoId': typeof DemosDemoIdRoute
  '/demos': typeof DemosRouteWithChildren
  '/demos/__layout': typeof Demos_layoutRoute
  '/demos/': typeof DemosIndexRoute
  '/(app)/dashboard/settings': typeof appDashboardSettingsRoute
  '/(app)/dashboard/': typeof appDashboardIndexRoute
  '/(app)/dashboard/employees/': typeof appDashboardEmployeesIndexRoute
  '/(app)/dashboard/users/': typeof appDashboardUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/unauthorized'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/demos/$demoId'
    | '/demos'
    | '/demos/'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/employees'
    | '/dashboard/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/unauthorized'
    | '/login'
    | '/register'
    | '/demos/$demoId'
    | '/demos'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/employees'
    | '/dashboard/users'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/about'
    | '/unauthorized'
    | '/(app)/dashboard'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/demos/$demoId'
    | '/demos'
    | '/demos/__layout'
    | '/demos/'
    | '/(app)/dashboard/settings'
    | '/(app)/dashboard/'
    | '/(app)/dashboard/employees/'
    | '/(app)/dashboard/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  appDashboardRouteRoute: typeof appDashboardRouteRouteWithChildren
  DemosDemoIdRoute: typeof DemosDemoIdRoute
  DemosRoute: typeof DemosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demos': {
      id: '/demos'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof DemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/': {
      id: '/demos/'
      path: '/'
      fullPath: '/demos/'
      preLoaderRoute: typeof DemosIndexRouteImport
      parentRoute: typeof DemosRoute
    }
    '/demos/__layout': {
      id: '/demos/__layout'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof Demos_layoutRouteImport
      parentRoute: typeof DemosRoute
    }
    '/demos/$demoId': {
      id: '/demos/$demoId'
      path: '/demos/$demoId'
      fullPath: '/demos/$demoId'
      preLoaderRoute: typeof DemosDemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/dashboard/': {
      id: '/(app)/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof appDashboardIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/settings': {
      id: '/(app)/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof appDashboardSettingsRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/users/': {
      id: '/(app)/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof appDashboardUsersIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
    '/(app)/dashboard/employees/': {
      id: '/(app)/dashboard/employees/'
      path: '/employees'
      fullPath: '/dashboard/employees'
      preLoaderRoute: typeof appDashboardEmployeesIndexRouteImport
      parentRoute: typeof appDashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface appDashboardRouteRouteChildren {
  appDashboardSettingsRoute: typeof appDashboardSettingsRoute
  appDashboardIndexRoute: typeof appDashboardIndexRoute
  appDashboardEmployeesIndexRoute: typeof appDashboardEmployeesIndexRoute
  appDashboardUsersIndexRoute: typeof appDashboardUsersIndexRoute
}

const appDashboardRouteRouteChildren: appDashboardRouteRouteChildren = {
  appDashboardSettingsRoute: appDashboardSettingsRoute,
  appDashboardIndexRoute: appDashboardIndexRoute,
  appDashboardEmployeesIndexRoute: appDashboardEmployeesIndexRoute,
  appDashboardUsersIndexRoute: appDashboardUsersIndexRoute,
}

const appDashboardRouteRouteWithChildren =
  appDashboardRouteRoute._addFileChildren(appDashboardRouteRouteChildren)

interface DemosRouteChildren {
  Demos_layoutRoute: typeof Demos_layoutRoute
  DemosIndexRoute: typeof DemosIndexRoute
}

const DemosRouteChildren: DemosRouteChildren = {
  Demos_layoutRoute: Demos_layoutRoute,
  DemosIndexRoute: DemosIndexRoute,
}

const DemosRouteWithChildren = DemosRoute._addFileChildren(DemosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  appDashboardRouteRoute: appDashboardRouteRouteWithChildren,
  DemosDemoIdRoute: DemosDemoIdRoute,
  DemosRoute: DemosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
