/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemosIndexRouteImport } from './routes/demos/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as Demos_layoutRouteImport } from './routes/demos/__layout'
import { Route as DemosDemoIdRouteImport } from './routes/demos/$demoId'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'

const DemosRouteImport = createFileRoute('/demos')()

const DemosRoute = DemosRouteImport.update({
  id: '/demos',
  path: '/demos',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosIndexRoute = DemosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemosRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const Demos_layoutRoute = Demos_layoutRouteImport.update({
  id: '/__layout',
  getParentRoute: () => DemosRoute,
} as any)
const DemosDemoIdRoute = DemosDemoIdRouteImport.update({
  id: '/demos/$demoId',
  path: '/demos/$demoId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demos/$demoId': typeof DemosDemoIdRoute
  '/demos': typeof Demos_layoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demos/': typeof DemosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demos/$demoId': typeof DemosDemoIdRoute
  '/demos': typeof DemosIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demos/$demoId': typeof DemosDemoIdRoute
  '/demos': typeof DemosRouteWithChildren
  '/demos/__layout': typeof Demos_layoutRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/demos/': typeof DemosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/dashboard/settings'
    | '/demos/$demoId'
    | '/demos'
    | '/dashboard/'
    | '/demos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard/settings'
    | '/demos/$demoId'
    | '/demos'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/dashboard/settings'
    | '/demos/$demoId'
    | '/demos'
    | '/demos/__layout'
    | '/dashboard/'
    | '/demos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  DemosDemoIdRoute: typeof DemosDemoIdRoute
  DemosRoute: typeof DemosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demos': {
      id: '/demos'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof DemosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/': {
      id: '/demos/'
      path: '/'
      fullPath: '/demos/'
      preLoaderRoute: typeof DemosIndexRouteImport
      parentRoute: typeof DemosRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/demos/__layout': {
      id: '/demos/__layout'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof Demos_layoutRouteImport
      parentRoute: typeof DemosRoute
    }
    '/demos/$demoId': {
      id: '/demos/$demoId'
      path: '/demos/$demoId'
      fullPath: '/demos/$demoId'
      preLoaderRoute: typeof DemosDemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface DemosRouteChildren {
  Demos_layoutRoute: typeof Demos_layoutRoute
  DemosIndexRoute: typeof DemosIndexRoute
}

const DemosRouteChildren: DemosRouteChildren = {
  Demos_layoutRoute: Demos_layoutRoute,
  DemosIndexRoute: DemosIndexRoute,
}

const DemosRouteWithChildren = DemosRoute._addFileChildren(DemosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  DemosDemoIdRoute: DemosDemoIdRoute,
  DemosRoute: DemosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
